trigger:
  batch: true
  branches:
    include:
    - main

variables:
- name: AZURE_STORAGE_CONTAINER
  value: $(container)
- name: AZURE_CONTAINER_CONNECTION_STRING
  value: $(connection_string)
- name: TEST_IMAGE_URL
  value: $(test_image)

stages:
- stage: BuildApp
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    - task: CmdLine@2
      displayName: 'Install dependencies and build'
      inputs:
        script: |
          npm install -g @nestjs/cli
          npm install
          npm run build

- stage: TestApp
  jobs:
  - job: Test
    steps:
    - task: CmdLine@2
      displayName: 'Run tests'
      inputs:
        script: |
          npm install
          npm run test:e2e
          
- stage: SyncRepository
  jobs:
  - job: SyncToGithub
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - -'
          Write-Host ' reflect Azure Devops repo changes to GitHub repo'
          Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - - '
          $stageDir = '$(Build.SourcesDirectory)' | Split-Path
          $githubDir = $stageDir +"\"+"gitHub"
          $destination = $githubDir +"\"+"AZURE_STORAGE_PACKAGE.git"
          #please provide your username
          $alias = 'KwobiaMtech:'+ "$(Github.PAT)"
          #Please make sure, you remove https from azure-repo-clone-url
          $sourceURL = 'https://$(AzureDevops.PAT)@dev.azure.com/dawoodiddris/AZURE_STORAGE_PACKAGE/_git/AZURE_STORAGE_PACKAGE'
          #Please make sure, you remove https from github-repo-clone-url
          $destURL = 'https://' + $alias + '@github.com/KwobiaMtech/azuredevopsdemo.git'
          #Check if the parent directory exists and delete
          if((Test-Path -path $githubDir))
          {
            Remove-Item -Path $githubDir -Recurse -force
          }
          if(!(Test-Path -path $githubDir))
          {
            New-Item -ItemType directory -Path $githubDir
            Set-Location $githubDir
            git clone --mirror $sourceURL
          }
          else
          {
            Write-Host "The given folder path $githubDir already exists";
          }
          Set-Location $destination
          Write-Output '*****Git removing remote secondary****'
          git remote rm secondary
          Write-Output '*****Git remote add****'
          git remote add --mirror=fetch secondary $destURL
          Write-Output '*****Git fetch origin****'
          git fetch $sourceURL
          Write-Output '*****Git push secondary****'
          git push --force secondary --all
          Write-Output '**Azure Devops repo synced with Github repo**'
          Set-Location $stageDir
          if((Test-Path -path $githubDir))
          {
          Remove-Item -Path $githubDir -Recurse -force
          }

